### ISSUE TITLE
Update to mocha from 1.3.0 to 1.11.2 breaks tests

### ISSUE THREAD

**Issue by Cruikshanks** [DEFRA/sroc-service-team#4]
There is a [dependabot PR](https://github.com/DEFRA/sroc-tcm-admin/pull/245) to update mocha that is currently failing.

```bash
/home/travis/build/DEFRA/sroc-tcm-admin/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.7/lib/active_support/dependencies.rb:292:in `require': cannot load such file -- mocha/mini_test (LoadError)
	from /home/travis/build/DEFRA/sroc-tcm-admin/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.7/lib/active_support/dependencies.rb:292:in `block in require'
	from /home/travis/build/DEFRA/sroc-tcm-admin/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.7/lib/active_support/dependencies.rb:258:in `load_dependency'
	from /home/travis/build/DEFRA/sroc-tcm-admin/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.7/lib/active_support/dependencies.rb:292:in `require'
	from /home/travis/build/DEFRA/sroc-tcm-admin/test/test_helper.rb:16:in `<top (required)>'
	from /home/travis/build/DEFRA/sroc-tcm-admin/test/controllers/exclusion_reasons_controller_test.rb:1:in `require'
	from /home/travis/build/DEFRA/sroc-tcm-admin/test/controllers/exclusion_reasons_controller_test.rb:1:in `<top (required)>'
	from /home/travis/build/DEFRA/sroc-tcm-admin/vendor/bundle/ruby/2.4.0/gems/railties-5.1.7/lib/rails/test_unit/runner.rb:50:in `require'
# ...
```

We either need to diagnose and fix the issue or lock the version of mocha.

**Comment by Cruikshanks** [comment]
Fixed in https://github.com/DEFRA/sroc-tcm-admin/pull/341
